### ISSUE TITLE
[SCA] Definition of model configuration to apply different data layout

### ISSUE THREAD

**Issue by clementval** [C2SM-RCM/claw-language-definition#12]
When using `parallelize` directive on several files, the probability that the same dimension is defined is big as the dimensions added will be similar for the whole model. Therefore, having the possibility to centralize this definition and ability to change it only in one place would be a good feature. Dimensions can also change depending on the target used for the transformation. Layout should be then also defined in this configuration file.

`parallelize` will be changed to `sca`

This issue is open to discuss the specification of this configuration file and its implication in the transformation process for the single column abstraction [SCA]. 

**Configuration file**
Configuration file would be written in TOML format (https://github.com/toml-lang/toml). 
It is a real format for configurations and has the advantage to be concise and allows comments as well as arrays and types.

```toml
# Model configuration
# To be done when requirements are defined

[model] # Definition of global model information
  name = "COSMO"

[dimension] # Definition of dimensions that can be used in layouts
  [dimension.horizontal]
    size.lower = 1 # Can be an integer value or a basic string
    size.upper = "ncol"
    # if iteration information are omitted, iteration size.lower to size.upper with a step 1 
    # is inferred. 
    

  [dimension.proma]
    size.lower = 1
    size.upper = "nproma"
    iteration.lower = "pstart"
    iteration.upper = "pend"
    iteration.step = 1 # If not specified, 1 by default

  [dimension.vertical]
    size.lower = 1
    size.upper = "klev"


[layout] # Definition of layouts and default for target
  [layout.default] # Will be used if no specific target layout specified
    position = [ "horizontal", 0 ]

  [layout.cpu] # Target specific layout for CPU
    position = [ "horizontal", "current", "proma" ]

  [layout.gpu] # Target specific layout for GPU
    position = [ "horizontal", "current" ]

  [layout.radiation] # Specialized layout for the radiation
    position = [ "current", "horizontal" ]
```

* At least one dimension should be defined.
* At least the `layout.default` should be defined.

Definition in the Fortran code
```fortran
module sca_demo

contains
  subroutine kernel1(a, b)
    ! Defines which fields are coming from the model and then needs
    ! to be promoted. Using the default layout
    ! Replace the !$claw define dimension x(1:n)
    !$claw model-data 
    real :: a
    real :: b(nlev)
    !$claw end model-data

    real :: c ! Would stay as a scalar

    !$claw sca ! Will replace the parallelize directive
    
  end subroutine kernel1

 subroutine kernel2(a, b)
    ! Using a specific layout
    ! Replace the !$claw define dimension x(1:n)
    !$claw model-data layout("radiation")
    real :: a
    real :: b(nlev)
    !$claw end model-data

    real :: c ! Would stay as a scalar

    !$claw sca ! Will replace the parallelize directive
    
  end subroutine kernel2

end module sca_demo
```
